emencia/django/newsletter/models.py
# -*- coding: utf-8 -*-
"""Models for emencia.django.newsletter"""
from smtplib import SMTP
from datetime import datetime
from datetime import timedelta
from hashids import Hashids

from django.conf import settings
from django.db import models
from django.utils.encoding import smart_str
from django.urls import reverse
from django.utils.translation import ugettext
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import Group

from emencia.django.newsletter.managers import ContactManager
from emencia.django.newsletter.settings import DEFAULT_HEADER_REPLY
from emencia.django.newsletter.settings import DEFAULT_HEADER_SENDER
from emencia.django.newsletter.settings import NEWSLETTER_BASE_PATH
# from emencia.django.newsletter.utils.vcard import vcard_contact_export

# Patch for Python < 2.6
try:
    getattr(SMTP, 'ehlo_or_helo_if_needed')
except AttributeError:
    def ehlo_or_helo_if_needed(self):
        if self.helo_resp is None and self.ehlo_resp is None:
            if not (200 <= self.ehlo()[0] <= 299):
                (code, resp) = self.helo()
                if not (200 <= code <= 299):
                    raise SMTPHeloError(code, resp)
    SMTP.ehlo_or_helo_if_needed = ehlo_or_helo_if_needed


class SMTPServer(models.Model):
    """Configuration of a SMTP server"""
    name = models.CharField(_('name'), max_length=255)
    host = models.CharField(_('server host'), max_length=255)
    user = models.CharField(_('server user'), max_length=128, blank=True,
                            help_text=_('Leave it empty if the host is public.'))
    password = models.CharField(_('server password'), max_length=128, blank=True,
                                help_text=_('Leave it empty if the host is public.'))
    port = models.IntegerField(_('server port'), default=25)
    tls = models.BooleanField(_('server use TLS'))

    headers = models.TextField(_('custom headers'), blank=True,
                               help_text=_('key1: value1 key2: value2, splitted by return line.'))
    mails_hour = models.IntegerField(_('mails per hour'), default=0)

    def connect(self):
        """Connect the SMTP Server"""
        smtp = SMTP(smart_str(self.host), int(self.port))
        smtp.ehlo_or_helo_if_needed()
        if self.tls:
            smtp.starttls()
            smtp.ehlo_or_helo_if_needed()

        if self.user or self.password:
            smtp.login(smart_str(self.user), smart_str(self.password))
        return smtp

    def credits(self):
        """Return how many mails the server can send"""
        return self.mails_hour
        if not self.mails_hour:
            return 1000 # Arbitrary value

        last_hour = datetime.now() - timedelta(hours=1)
        sent_last_hour = ContactMailingStatus.objects.filter(
            models.Q(status=ContactMailingStatus.SENT) |
            models.Q(status=ContactMailingStatus.SENT_TEST),
            newsletter__server=self,
            creation_date__gte=last_hour).count()
        return self.mails_hour - sent_last_hour

    @property
    def custom_headers(self):
        if self.headers:
            headers = {}
            for header in self.headers.split('\r\n'):
                if header:
                    key, value = header.split(':')
                    headers[key.strip()] = value.strip()
            return headers
        return {}

    def __str__(self):
        return '%s (%s)' % (self.name, self.host)

    class Meta:
        verbose_name = _('SMTP server')
        verbose_name_plural = _('SMTP servers')


class HashContactManager(ContactManager):
    ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'
    MIN_LENGTH = 7
    SALT = 'edn' + settings.SECRET_KEY

    def to_hashid(self, i):
        h = Hashids(salt=self.SALT, alphabet=self.ALPHABET, min_length=self.MIN_LENGTH)
        return self.ALPHABET[i%len(self.ALPHABET)]+h.encode(i)

    def from_hashid(self, i):
        i = i[1:]
        h = Hashids(salt=self.SALT, alphabet=self.ALPHABET, min_length=self.MIN_LENGTH)
        ids = h.decode(i)
        if len(ids):
            return ids[0]
        else:
            return 0

    def get_by_hashid(self, hashid):
        id = self.from_hashid(hashid)
        return self.get_queryset().get(id=id)


class Contact(models.Model):
    """Contact for emailing"""
    email = models.EmailField(_('email'), unique=True)
    title = models.CharField(_('Bezeichnung'), max_length=255, blank=True)
    degree = models.CharField(_('Titel'), max_length=50, blank=True)
    company = models.CharField(_('Firma'), max_length=255, blank=True)
    salutation = models.CharField(_('Anrede'), max_length=50, blank=True)
    first_name = models.CharField(_('first name'), max_length=100, blank=True)
    last_name = models.CharField(_('last name'), max_length=100, blank=True)

    subscriber = models.BooleanField(_('subscriber'), default=True)
    valid = models.BooleanField(_('valid email'), default=True)
    tester = models.BooleanField(_('contact tester'), default=False)

    content_type = models.ForeignKey(ContentType, blank=True, null=True, on_delete=models.PROTECT)
    object_id = models.PositiveIntegerField(blank=True, null=True)
    content_object = GenericForeignKey('content_type', 'object_id')

    creation_date = models.DateTimeField(_('creation date'), auto_now_add=True)
    modification_date = models.DateTimeField(_('modification date'), auto_now=True)

    activation_date = models.DateTimeField(_('Bestätigungsdatum'), null=True, blank=True)

    import_id = models.CharField(_('ImportID'), editable=False, null=True, blank=True, max_length=255)
    source = models.CharField(_('Quelle'), default="web", max_length=20)
    syncing = models.BooleanField(_('wird synchronisiert'), default=False, editable=False)

    objects = HashContactManager()

    def subscriptions(self):
        """Return the user subscriptions"""
        return MailingList.objects.filter(subscribers=self)

    def unsubscriptions(self):
        """Return the user unsubscriptions"""
        return MailingList.objects.filter(unsubscribers=self)

    def vcard_format(self):
        return vcard_contact_export(self)

    def mail_format(self):
        if self.first_name and self.last_name:
            return '%s %s <%s>' % (self.last_name, self.first_name, self.email)
        return self.email
    mail_format.short_description = _('mail format')

    def get_absolute_url(self):
        if self.content_type and self.object_id:
            return self.content_object.get_absolute_url()
        return reverse('admin:newsletter_contact_change', args=(self.pk,))

    def __str__(self):
        if self.first_name and self.last_name:
            return '%s %s' % (self.last_name, self.first_name)
        return '%s' % self.email

    class Meta:
        ordering = ('creation_date',)
        verbose_name = _('contact')
        verbose_name_plural = _('contacts')

    def get_hashid(self):
        return Contact.objects.to_hashid(self.id)


class MailingList(models.Model):
    """Mailing list"""
    name = models.CharField(_('name'), max_length=255)
    description = models.TextField(_('description'), blank=True)

    subscribers = models.ManyToManyField(Contact, verbose_name=_('subscribers'),
                                         related_name='mailinglist_subscriber')
    unsubscribers = models.ManyToManyField(Contact, verbose_name=_('unsubscribers'),
                                           related_name='mailinglist_unsubscriber', blank=True)

    creation_date = models.DateTimeField(_('creation date'), auto_now_add=True)
    modification_date = models.DateTimeField(_('modification date'), auto_now=True)

    def subscribers_count(self):
        return self.subscribers.all().count()
    subscribers_count.short_description = _('subscribers')

    def unsubscribers_count(self):
        return self.unsubscribers.all().count()
    unsubscribers_count.short_description = _('unsubscribers')

    def expedition_set(self):
        unsubscribers_id = self.unsubscribers.values_list('id', flat=True)
        return self.subscribers.valid_subscribers().exclude(
            id__in=unsubscribers_id)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('creation_date',)
        verbose_name = _('mailing list')
        verbose_name_plural = _('mailing lists')


class MultiMailingListWrapper(object):
    def __init__(self, newsletter):
        self.newsletter = newsletter

    def expedition_set(self):
        ids = []
        for mailing_list in self.newsletter.mailing_lists.all():
            ids += list(mailing_list.expedition_set().values_list('id', flat=True))
        return Contact.objects.filter(id__in=ids)

    @property
    def unsubscribers(self):
        ids = []
        for mailing_list in self.newsletter.mailing_lists.all():
            ids += list(mailing_list.unsubscribers.values_list('id', flat=True))
        return Contact.objects.filter(id__in=ids)

    @property
    def subscribers(self):
        ids = []
        for mailing_list in self.newsletter.mailing_lists.all():
            ids += list(mailing_list.subscribers.values_list('id', flat=True))
        return Contact.objects.filter(id__in=ids)

    @property
    def name(self):
        names = list(self.newsletter.mailing_lists.values_list('name', flat=True))
        return ", ".join(names)

    def subscribers_count(self):
        return self.subscribers.all().count()
    subscribers_count.short_description = _('subscribers')

    def unsubscribers_count(self):
        return self.unsubscribers.all().count()
    unsubscribers_count.short_description = _('unsubscribers')

    def __str__(self):
        return ", ".join([l.name for l in self.newsletter.mailing_lists.all()])



class Newsletter(models.Model):
    """Newsletter to be sended to contacts"""
    DRAFT  = 0

emencia/django/newsletter/views/newsletter.py
"""Views for emencia.django.newsletter Newsletter"""
from django.template import RequestContext
from django.shortcuts import get_object_or_404
from django.shortcuts import render

from django.contrib.sites.models import Site
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string as render_file

from emencia.django.newsletter.models import Newsletter
from emencia.django.newsletter.models import ContactMailingStatus
from emencia.django.newsletter.utils import render_string
from emencia.django.newsletter.utils.newsletter import body_insertion
from emencia.django.newsletter.utils.newsletter import track_links
from emencia.django.newsletter.utils.tokens import untokenize
from emencia.django.newsletter.settings import (TRACKING_LINKS,
                                                HTML_TEMPLATE,
                                                TEXT_TEMPLATE,
                                                SEND_PLAINTEXT)


def render_newsletter(request, slug, context):
    """Return a newsletter in HTML format"""
    newsletter = get_object_or_404(Newsletter, slug=slug)
    context.update({'newsletter': newsletter,
                    'domain': Site.objects.get_current().domain})

    content = render_string(newsletter.content, context)
    title = render_string(newsletter.title, context)
    if TRACKING_LINKS:
        content = track_links(content, context)
    # unsubscription = render_file('newsletter/newsletter_link_unsubscribe.html', context)
    # content = body_insertion(content, unsubscription, end=True)

    template = 'newsletter/newsletter_detail.html'
    if HTML_TEMPLATE or TEXT_TEMPLATE:
        template = SEND_PLAINTEXT and TEXT_TEMPLATE or HTML_TEMPLATE

    context.update({'content': content,
                    'title': title,
                    'object': newsletter,
                    'PREVIEW' : True
                  })

    return render(request, template, context)


@login_required
def view_newsletter_preview(request, slug):
    """View of the newsletter preview"""
    context = {'contact': request.user,
               'preview' : True }
    return render_newsletter(request, slug, context)

def view_newsletter_contact(request, slug, uidb36, token):
    """Visualization of a newsletter by an user"""
    newsletter = get_object_or_404(Newsletter, slug=slug)
    contact = untokenize(uidb36, token)
    log = ContactMailingStatus.objects.create(newsletter=newsletter,
                                              contact=contact,
                                              status=ContactMailingStatus.OPENED_ON_SITE)
    context = {'contact': contact,
               'uidb36': uidb36, 'token': token}

    return render_newsletter(request, slug, context)

emencia/django/newsletter/templates/newsletter/base.html
{% extends "base.html" %}

emencia/django/newsletter/templates/newsletter/contact_import.html
{% extends "admin/base_site.html" %}
{% load i18n adminmedia %}

{% block breadcrumbs %}
{% if not is_popup %}
<div class="breadcrumbs">
     <a href="../../../">{% trans "Home" %}</a> &rsaquo;
     <a href="../../">{{ app_label|capfirst|escape }}</a> &rsaquo;
     <a href="../">{{ opts.verbose_name_plural|capfirst }}</a> &rsaquo;
     {% trans 'Importation' %}
</div>
{% endif %}
{% endblock %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% admin_media_prefix %}css/forms.css" />{% endblock %}

{% block content %}
<div id="content-main">
  <p>Importez les contacts de votre client mail favoris, en fournissant un fichier VCard.</p>
    <form action="." method="post" enctype="multipart/form-data">
    <div>
      <fieldset class="module aligned">
        <div class="form-row source">
          <div>
            <label for="id_source" class="required">Fichier VCard (.cvf) :</label>
            <input name="source" id="id_source" type="file" class="vTextField" />
          </div>
        </div>
      </fieldset>
      <div class="submit-row">
        <input type="submit" class="default" value="Importation" />
      </div>
    </div>
  </form>
</div>
{% endblock %}

emencia/django/newsletter/templates/newsletter/mailing_list_subscribe.html
{% extends "newsletter/base.html"%}
{% load i18n %}

{% block title %}{% trans "Subscription to mailing list" %}{% endblock %}

{% block content %}
<h2>{% trans "Subscription to mailing list" %}</h2>

{% if subscribed %}
<p>{% trans "Thanks for your subscription!" %}</p>
{% else %}
{% if mailing_list %}
<h3>{{ mailing_list }}</h3>
{{ mailing_list|linebreaks }}
{% else %}
<p>{% trans "Validate this form to subscribe to the mailing lists." %}</p>
{% endif %}
<form action="." method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="{% trans "Subscribe" %}" />
</form>
{% endif %}

{% endblock %}

emencia/django/newsletter/templates/newsletter/mailing_list_unsubscribe.html
{% extends "newsletter/base.html"%}
{% load i18n %}

{% block title %}{% trans "Unsubscription" %}{% endblock %}

{% block content %}
<h2>{% trans "Unsubscription" %}</h2>
{% if already_unsubscribed %}
 <p>{% trans "You are unsubscribed for this mailing list." %}</p>
{% else %}
 <p>{% trans "Validate this form to unsubscribe to this mailing list." %}</p>
 <form action="." method="post">
   <input type="text" value="{{ email }}" name="email" readonly />
   <input type="submit" value="{% trans "Unsubscribe" %}" />
 </form>
{% endif %}
{% endblock %}

emencia/django/newsletter/templates/newsletter/newsletter_density.html
<html>
  <head>
    <style type="text/css">
     .link_layout{ filter : alpha(opacity=70); -moz-opacity : 0.7; opacity : 0.7; border: 1px solid red;}
    </style>
    <script type="text/javascript" src="{{ NEWSLETTER_MEDIA_URL }}js/jquery.js"></script>
    <script type="text/javascript" src="{{ NEWSLETTER_MEDIA_URL }}js/jquery.heatcolor.js"></script>
    <script type="text/javascript">
      var top_links = [{% for tl in top_links %}"{{ tl.link.url|safe }}",{% endfor %}];
      var top_links_score = new Array();
      {% for tl in top_links %}
      top_links_score["{{ tl.link.url|safe }}"] = "{{ tl.total_clicks }}";
      {% endfor %}

      function create_overlay(top, left, width, height, score) {
        $("<div>", {"style": "position: absolute; width: "+ width +"px; height: "+ height +"px; top:" + top + "px; left:" + left + "px;",
	            "text": score,
	            "class": "link_layout"}).appendTo("#density_overlay");
      }

      $(document).ready(function(){
        $("a").each(function(a){
          var link = $(this);
	  var href = link.attr("href");

          if (jQuery.inArray(href, top_links) != -1) {
            var position = link.position();
            create_overlay(position.top - 3, position.left - 3, link.width() + 4, link.height() + 4,
                           top_links_score[href]);
          }
	});
	$("div.link_layout").heatcolor(
	  function() { return $(this).text(); },
	   {lightness: 0, colorStyle: 'greentored', reverseOrder: true });
      });
    </script>
    <title>{% block title %}{{ object.title }}{% endblock %}</title>
  </head>
  <body>
    <div id="density_overlay"></div>
    {% block body %}
    {{ object.content|safe }}
    {% endblock %}
  </body>
</html>

emencia/django/newsletter/templates/newsletter/newsletter_detail.html
<html>
  <head>
    <title>{% block title %}{{ title }}{% endblock %}</title>
  </head>
  {% block body %}
    {{ content|safe }}
  {% endblock %}
</html>

emencia/django/newsletter/templates/newsletter/newsletter_historic.html
{% extends "admin/change_list.html" %}
{% load i18n %}

{% block bodyclass %}change-list historic{% endblock %}

{% block breadcrumbs %}
{% if not is_popup %}
<div class="breadcrumbs">
     <a href="{% url 'admin:index' %}">{% trans "Admin." %}</a> &rsaquo;
     <a href="{% url 'admin:app_list' "newsletter" %}">{{ app_label|capfirst|escape }}</a> &rsaquo;
     <a href="{% url 'admin:newsletter_newsletter_changelist' %}">{{ opts.verbose_name_plural|capfirst }}</a> &rsaquo;
     {{ title }}
</div>
{% endif %}
{% endblock %}

{% block content %}
<div id="content-main">
  <div class="module" id="changelist">
    <table cellspacing="0">
      <thead>
	<tr>
	  <th>{% trans "Date" %}</th>
	  <th>{% trans "Contact" %}</th>
	  <th>{% trans "Action" %}</th>
	</tr>
      </thead>
      <tbody>
	{% for event in original.contactmailingstatus_set.all %}
	<tr class="{% cycle "row1" "row2" %}">
	  <td class="nowrap">{{ event.creation_date|date:"d F Y, H:i" }}</td>
	  <td>{{ event.contact.mail_format }}</td>
	  <td>{{ event.get_status_display }} {% if event.link %}{{ event.link.url|urlize }}{% endif %}</td>
	</tr>
	{% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

emencia/django/newsletter/templates/newsletter/newsletter_image_tracking.html
<img src="http://{{ domain }}{% url 'newsletter_newsletter_tracking' slug=newsletter.slug uidb36=uidb36 token=token %}" width="1" height="1" />

emencia/django/newsletter/templates/newsletter/newsletter_link_site.html
<div id="links">
  <a name="links"></a>
  <p>
    Si vous ne pouvez visualiser cet email,
    <a href="http://{{ domain }}{% url 'newsletter_newsletter_contact' slug=newsletter.slug uidb36=uidb36 token=token %}">cliquez ici</a>.
  </p>
</div>

emencia/django/newsletter/templates/newsletter/newsletter_link_unsubscribe.html
<div id="unsubscription">
  <a name="unsubscription"></a>
  <p>
    Pour vous d&eacute;sabonner de cette liste de diffusion, 
    <a href="{% if uidb36 and token %}http://{{ domain }}{% url 'newsletter_mailinglist_unsubscribe' slug=newsletter.slug uidb36=uidb36 token=token %}{% else %}#{% endif %}">cliquez ici</a>.
  </p>
</div>

emencia/django/newsletter/templates/newsletter/newsletter_statistics.html
{% extends "admin/change_list.html" %}
{% load i18n %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}change-list dashboard{% endblock %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="/static/admin/css/dashboard.css" />{% endblock %}

{% comment %}
{% block extrahead %}
<script type="text/javascript" src="{{ NEWSLETTER_MEDIA_URL }}js/jquery.js"></script>
<script type="text/javascript" src="{{ NEWSLETTER_MEDIA_URL }}js/jquery.form.js"></script>
<script type="text/javascript" src="{{ NEWSLETTER_MEDIA_URL }}js/swfobject/swfobject.js"></script>

<script type="text/javascript">
OFC = {};

OFC.jquery = {
    name: "jQuery",
    version: function(src) { return $('#'+ src)[0].get_version() },
    rasterize: function (src, dst) { $('#'+ dst).replaceWith(OFC.jquery.image(src)) },
    image: function(src) { return "<img src='data:image/png;base64," + $('#'+src)[0].get_img_binary() + "' />"},
    popup: function(src) {
        var img_win = window.open('', 'Charts: Export as Image')
        with(img_win.document) {
            write('<html><head><title>Charts: Export as Image<\/title><\/head><body>' + OFC.jquery.image(src) + '<\/body><\/html>') }
      // stop the 'loading...' message
      img_win.document.close();
     }
}

if (typeof(Control == "undefined")) {var Control = {OFC: OFC.jquery}}

function save_image() { OFC.jquery.popup('charts_view'); }

$(document).ready(function(){
  swfobject.embedSWF("{{ NEWSLETTER_MEDIA_URL }}swf/open-flash-chart.swf", "charts_view", "498", "350", "9.0.0",
                     "{{ NEWSLETTER_MEDIA_URL }}js/swfobject/expressInstall.swf",
                     {"data-file": "{% url 'newsletter_newsletter_charts' object.slug %}"});

  function reload_charts(charts_data) {
    swfobject.getObjectById("charts_view").load(charts_data);
  };

  function validate(formData, jqForm, options) {
    for (var i=0; i < formData.length; i++) {
        if (formData[i].name == 'start') {
    var start = parseInt(formData[i].value);
        }
        if (formData[i].name == 'end') {
    var end = parseInt(formData[i].value);
        }
    }
    if (start > end) {
      return false;
    }
  };

  var options = {success: reload_charts,
                 beforeSubmit: validate};
  $("#period_selector").ajaxForm(options);
});
</script>
{% endblock %}
{% endcomment %}

{% block breadcrumbs %}
{% if not is_popup %}
<div class="breadcrumbs">
     <a href="{% url 'admin:index' %}">{% trans "Admin." %}</a> &rsaquo;
     <a href="{% url 'admin:app_list' "newsletter" %}">{{ app_label|capfirst|escape }}</a> &rsaquo;
     <a href="{% url 'admin:newsletter_newsletter_changelist' %}">{{ opts.verbose_name_plural|capfirst }}</a> &rsaquo;
     {{ title }}
</div>
{% endif %}
{% endblock %}

{% block content %}
<div id="content-main">
  <!-- Receptions -->
  <div class="module" id="reception">
    <table summary="{% trans "Broadcasting statistics" %}">
      <caption><a href="#" class="section">{% trans "Broadcasting statistics" %}</a></caption>
      <tr>
        <th scope="row">{% trans "Total openings" %}</th>
	<td>&nbsp;</td>
        <td>{{ stats.total_openings }}</td>
      </tr>
      {# <tr> #}
        {# <th scope="row">{% trans "Openings on site" %}</th> #}
        {# <td>{{ stats.total_on_site_openings }}</td> #}
        {# <td>{{ stats.unique_on_site_openings }}</td> #}
      {# </tr> #}
      <tr>
        <th scope="row">{% trans "Total openings unique" %}</th>
        <td>{{ stats.unique_openings }}</td>
	<td>{{ stats.unique_openings_percent|floatformat:2 }}%</td>
      </tr>
      <tr>
        <th scope="row">{% trans "Unknow delivery" %}</th>
        <td>{{ stats.unknow_openings }}</td>
	<td>{{ stats.unknow_openings_percent|floatformat:2 }}%</td>
      </tr>
      {# <tr> #}
        {# <th scope="row">{% trans "Unsubscriptions" %}</th> #}
        {# <td>{{ stats.total_unsubscriptions }}</td> #}
	{# <td>{{ stats.total_unsubscriptions_percent|floatformat:2 }}%</td> #}
      {# </tr> #}
      <tr>
        <th scope="row">{% trans "Openings average" %}</th>
        <td>&nbsp;</td>
        <td>{{ stats.opening_average|floatformat:2 }}</td>
      </tr>
    </table>
  </div>
  <!-- Links -->
  <div class="module" id="reception">
    <table summary="{% trans "Links statistics" %}">
      <caption><a href="#" class="section">{% trans "Links statistics" %}</a></caption>
      <tr>
        <th scope="row">{% trans "Total clicked links" %}</th>
        <td>{{ stats.total_clicked_links }}</td>
        <td>{{ stats.total_clicked_links_percent|floatformat:2 }}%</td>
      </tr>
      <tr>
        <th scope="row">{% trans "Total clicked links unique" %}</th>
        <td>{{ stats.unique_clicked_links }}</td>
        <td>{{ stats.unique_clicked_links_percent|floatformat:2 }}%</td>
      </tr>
      <tr>
        <th scope="row">{% trans "Clicked links by openings" %}</th>
	<td>&nbsp;</td>
        <td>{{ stats.clicked_links_by_openings|floatformat:2 }}%</td>
      </tr>
      <tr>
        <th scope="row">{% trans "Clicked links average" %}</th>
	<td>&nbsp;</td>
        <td>{{ stats.clicked_links_average|floatformat:2 }}</td>
      </tr>
    </table>
  </div>
  {% if period %}
  <div class="module" id="charts_options">
    <form id="period_selector" action="{% url 'newsletter_newsletter_charts' object.slug %}" method="post">
      <table summary="{% trans "Consultation histogram" %}">
	<tr>
	  <th scope="row" style="vertical-align: middle;">
	    {% trans "Period" %} :
	  </th>
	  <td>
	    <select name="start">
	      {% for date in period %}
	      <option value="{{ forloop.counter0 }}" {% ifequal forloop.counter0 0 %}selected="selected"{% endifequal %}>{{ date|date:"d M Y" }}</option>
	      {% endfor %}
	    </select>
	    <span>-></span>
	    <select name="end">
	      {% for date in period %}
	      <option value="{{ forloop.counter0 }}" {% ifequal forloop.counter0 6 %}selected="selected"{% endifequal %}>{{ date|date:"d M Y" }}</option>
	      {% endfor %}
	    </select>
	  </td>
	  <td><input type="submit" value="OK" /></td>
	</tr>
      </table>
    </form>
  </div>
  {% endif %}
</div>
{% endblock %}

{% block sidebar %}
<div id="content-related">
    {# <div class="module" id="report-module"> #}
      {# <h2>{% trans "Report" %}</h2> #}
      {# <h3> #}
	{# <a href="{% url 'newsletter_newsletter_report' object.slug %}">{% trans "Download CSV report" %}</a> #}
      {# </h3> #}
      {# <p></p> #}
    {# </div> #}
    <div class="module" id="general-informations-module">
        <h2>{% trans "Informations" %}</h2>
        <h3>{% trans "Recipients" %} <span class="quiet">{{ stats.mails_to_send }}</span></h3>
  <ul>
  {% for mlist in object.mailing_lists.all  %}
  <li><a href="{% url 'admin:newsletter_mailinglist_change' mlist.pk %}">{{ mlist.name }}</a> <span class="quiet">{{ mlist.subscribers.count }}</span></li>
  {% endfor %}
  </ul>

  <br />
  <h3>{% trans "Status" %}</h3>
	<p>{{ object.get_status_display }} {% if stats.remaining_mails %}<span class="quiet">({{ stats.mails_sent }}/{{ stats.mails_to_send }})</span>{% endif %}</p>

  <br />
	<h3>{% trans "Sending date" %}</h3>
	<p>{{ object.sending_date|date:"d M Y H:i" }}</p>
	{% if stats.tests_sent %}

  <br />
	<h3>{% trans "Tests sent" %}</h3>
	<p>{{ stats.tests_sent }}</p>
	{% endif %}
  </div>

  <div class="module" id="top-links-module">
	<h3>{% trans "Top Links" %} </h2>
	<ul class="">
	{% for top_link in stats.top_links %}
	<li><a href="{{ top_link.link.url }}" title="{{ top_link.link.title }}" target="blank">{{ top_link.link.title|slice:":23" }}</a>
	  <span class="quiet">({{ top_link.total_clicks }} Klicks)</span>
	  {# <span class="mini quiet">({{ top_link.unique_clicks }})</span> #}
	</li>
	{% empty %}
	<li>{% trans "No Top Links yet." %}</li>
	{% endfor %}
	</ul>
    </div>
</div>
{% endblock %}